### ISSUE TITLE
Updating OEC member data

### ISSUE THREAD

**Issue by acka47** [ocwc/ocwc-members#3]
Merging duplicates that where introduced with integrating OEC member data (see https://github.com/hbz/oerworldmap/issues/255) , I noticed that the OEC member data often isn't up-to-date. See e.g. https://oerworldmap.org/resource/urn:uuid:7069908c-77eb-11e5-9f9f-c48e8ff4ea31 where the address isn't up-to-date and maybe the name isn't the current official name.

I also found outdated addresses for other organizations I looked at (which are deleted by now in the worldmap): Open university (member id 139), Creative Commons (id 227), OER Africa (226).
  
This might be an incentive for OEC to sync with OER worldmap or even use OER worldmap as the place to curate its member data.  

@gandalfar Is it right that the data isn't regulary updated after a record is stored? Are there any thoughts at OEC to somehow sync with or use the OER worldmap?

**Comment by gandalfar** [comment]
Ok, a few things about our API:
 - It should only return currently active members. So if a member decides to stop being our member, it will disappear from our API.
 - We usually update administrative member data when our members notify us. The second time when this often happens is, when we invoice them and they realise that their old name is on the invoice. So only about once a year.
 - We only display membership data on city level on our map. It's very rare that our members would switch address to a different city.

If you can e-mail us a difference list, every 3 or 6 months, we can manually update the data on our side. I'm not sure the data changes often enough to warrant automated sync.

**Comment by acka47** [comment]
Thanks for the information about data updates and for the clarification about address data on city-level. Good to know that you keep your data up-to-date on a yearly basis. That sounds good to me.

Regarding the addresses: Somehow street-level addresses where added during the conversion process for the OER worldmap APUI – but they are probably all wrong. We will have to fix this on our side...

Closing this issue for now.
